### ISSUE TITLE
Support streams as a plugin

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1111]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
Streams are not supported

**Expected behavior**
Streams as a resource should be supported

**Tasks**
- [x] #1112 - Extract designer page's header from flow.component as a common component so that it can  be used for streams and flows 
- [x] Add streams as a plugin in client
- [x] Add stream's as a plugin in server
- [x] Export applications with stream resources #1149 
- [x] Import applications with stream resources #1150 
- [x] Validations for stream resources (while exporting, importing, creating and updating) #1179
- [x] Styling changes as per the designs #1184
- [x] Creating a special application JSON for run stimulation 
- [x] Add / Manage triggers of the stream - #1122 
- [x] Add / Manage the stages (like tasks for flows) of the stream - #1123 
- [x] Add / Manage the input / output params of the stream - #1124 
- [x] Add Run Stimulation for the streams
- [x] Add the stream's stimulation results in the context panel
