### ISSUE TITLE
Stream Simulation: Allow mapping data headers to pipeline inputs

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1200]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
While running a stream simulation, the headers of the csv file provided are automatically mapped to the pipeline's inputs which are defined with the same name. The stream simulation ignores a column of the data which has no pipeline input with same name. 

**Expected behavior**
User should be allowed to opt one of the following different strategies to map the csv data to the pipeline inputs:

- [x] 1. Single input (whole data to one pipeline input) [#1235]
- [x] 2. Auto mapping by columns (map the inputs of pipeline to column with same name of the data) [#1235]
- [ ] 3. Customize mapping by columns (map the inputs of pipeline to any column of data with some calculation involved) Separately tracked in #1243
