### ISSUE TITLE
Support custom icons for contributions

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#1261]
## Description

Allow activity and trigger contributions to have custom icons.

Currently all triggers and activities look the same, having custom icons will help to differentiate them better in a flow.

## Describe the solution you'd like

The contribution will be able to optionally define a custom icon, when the custom icon is present it will be displayed as the corresponding icon for usages of the contribution in the UI.

If the contribution doesn't define an icon or no icon is present then the default activity or trigger icon should be used.

We need to figure out if we want the icon to be provided by configuration or by convention:

1. If by configuration then the `descriptor.json` needs to define a new property that will specify where to search for the image. The contributor needs to add the image file to their files and update their `descriptor.json` to point to that image.
2. If by convention then the UI can look for a specific file in the contribution's root folder, this way contributors only have to put an image in their contribution files, this is similar to the way the `descriptor.json` works. For example, if we define the convention that image should be named `icon` then the UI needs to try to find that file and if not found then fallbacks to the default icon. For this one we also need to provide a list of possible image formats and and priority for them, for example the UI can try to find `icon.svg` and if not found then search for `icon.png` and if not found then consider that no custom icon was provided and use the default icon.
3. A combination of the options above where the UI tries option 1 and if no configuration specified in the `descriptor.json` then tries option 2.

## Describe alternatives you've considered

An alternative option is to have a pre-defined set of icons or categories and the contributor can specify one of the icons or categories in their descriptor.json

## TO-DO
- [x] Define if icon should be loaded by configuration or by convention
- [x] Define allowed image formats
- [x] Define allowed file sizes
- [x] Figure out the best way to provide the icons from the backend to the frontend (maybe the file references are inspected and saved during contributions load)

**Comment by ppaidi** [comment]
Fixed in the PR's #1309 #1320 #1322 #1323 #1324 #1325
