### ISSUE TITLE
Replace ng2-bs3-modal for modals

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#900]
Remove ng2-bs3-dependency so we can also remove jQuery and boostrap js dependency.

Part of https://github.com/TIBCOSoftware/flogo-web/issues/881

- [x] New Flow Modal [PR #892]
- [x] Export Flows Modal  [PR #888] 
- [x] Build shim triggers modal [PR #892 ]
- [x] Define Input/Output params modal
- [x] Add new Trigger modal
- [x] Install New Activity/Trigger modal
- [x] App Import Message Modal - [PR #926]
- [x] Select subflow modal

Removed components:
~- [ ] Walkthrough Modal~
~- [ ] Device properties - device profile~
~- [ ] Select Profile Modal - [PR #926]~

Modals to be Changed | File/component name
-- | --
Select Profile Modal | new-app.component
New Flow Modal | new-flow.component
Export Flows Modal | export-flows.component
Build shim triggers modal | shim-trigger.component
Define Input/Output params modal | params-schema.component
Add new Trigger modal | select-trigger.component
Install New Activity/Trigger modal | Installer.component
Device properties - device profile | settings.tpl
App Import Message Modal | app-import.component
Walkthrough Modal | walkthrough.component
Select subflow modal | sub-flow.component

**Comment by fcastill** [comment]
resolved in #1228
