### ISSUE TITLE
Epic: Resource modularization

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#938]
- [x] Investigate monorepo tools (tooling)
- [x] Setup monorepo tools (tooling)
- [x] Define server plugin architecture (server)
- [x] Implement server plugin loading mechanism (server)
- [x] Register resource type (server)
- [x] List resource types (server)
- [x] Create resource (server)
- [x] Get resource (server)
- [x] Update resource (server)
- [x] Delete resource (server)
- [x] Import a resource (server)
- [x] Export a resource (server)
- [x] Extract/convert flow into a resource plugin (server)
- [x] Update UI to support new server models / API changes (client)
- [x] Allow to register new resource types (client)
- [x] Allow to select resource type when creating a new resource (client)
- [x] Display resources in app page (client)
- [x] Define client plugin architecture (client)
- [x] Implement client plugin loading mechanism (client)
- [x] Implement client plugin APIs (@flogo-web/core) (client)
- [x] Implement plugin resource loading and inject dependencies (like flow designer) (client)
- [x] Extract/refactor flow designer to client plugin (client)
- [x] Test/adjust production build process (minification, tree shaking, AOT, etc.) (client/tooling)
- [x] Custom build process (cicd/tooling)
- [ ] Client plugin docs (docs)
- [ ] Server plugin docs (docs)

**Bugs**
- [x] Deleting trigger redirects to home page [ #997 ]
